version: '3.8'

services:
  postgres:
    image: postgres:17.4-alpine
    ports:
      - "5432:5432"
    container_name: pack_db
    environment:
      POSTGRES_USER: pack_admin
      POSTGRES_PASSWORD: pack_password
      POSTGRES_DB: pack_db
    volumes:
      - pack_db_data:/var/lib/postgresql/data

volumes:
  pack_db_data:
